### ISSUE TITLE
Two user models

### ISSUE THREAD

**Issue by SebastiaanKloos** [gpasztor87/oc-jwt-auth#4]
I have two user models. Front and back-end. I use this plugin with your oc-api-plugin. Is it possible to create two kind of API's. So each model uses one API. Or can I add multiple user models to the config file? Then I would make my own logic to check which user is front or back-end.

**Comment by gpasztor87** [comment]
Hi,

yes, if you want to add multiple User model, you need to update the AuthController's authenticate method like this:
```php
$credentials = $request->only('username', 'password');

try {
      Config::set('jwt.user', 'Backend\Models\User');
      Config::set('jwt.providers.auth', 'Autumn\JWTAuth\Classes\BackendAuthAdapter');
      if (! $token = JWTAuth::attempt($credentials)) {
            return response()->json(['error' => 'invalid_credentials'], 401);
     }
} catch (JWTException $ex) {
      return response()->json(['error' => 'could_not_create_token'], 500);
}

return response()->json(compact('token'));
```

Finally you need to modify or reimplement the RainAuthAdapter class.

**Comment by SebastiaanKloos** [comment]
Thanks. That is exactly what I needed!

**Comment by SebastiaanKloos** [comment]
I tried creating the BackendAuthAdapter myself. Unfortunately my credentials are not being accepted. Do you have any idea what could possibly be wrong?

**Comment by SebastiaanKloos** [comment]
You used username in your example but it needs to be the login attribute. Everything is working now!
