### ISSUE TITLE
installing and routing problems

### ISSUE THREAD

**Issue by danielschweiger** [gpasztor87/oc-jwt-auth#6]
hi,

after composer install I tried to:

`[09:00 PM]-[vagrant@machine1]-[/var/www/www.server.local] 
$ php artisan vendor:publish --provider="Autumn\JWTAuth\ServiceProvider"
`

but:

`Nothing to publish for tag [].`

then I inserted this by hand:

config/app.php:

`
'providers' => array_merge(include(base_path('modules/system/providers.php')), [

        // 'Illuminate\Html\HtmlServiceProvider', // Example

        'System\ServiceProvider',
        'Autumn\JWTAuth\ServiceProvider',
    ]),`

then after a php artisan cache:clear I was able to:

`php artisan jwt:generate`
`jwt-auth secret [PSC0zVUxPpcRjP3tOtNEJkj3mVfAlgho] set successfully.`

Now when I try to POST username and password to /auth/login with Postman I get a 404.
POSTing to /v1/auth/login also returns 404.

The routes file ist standard:

`$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->post('auth/login', 'Autumn\JWTAuth\Http\Controllers\AuthController@authenticate');
    $api->post('auth/register', 'Autumn\JWTAuth\Http\Controllers\AuthController@register');
});`

Did I missed something?

**Comment by gpasztor87** [comment]
Hi!

Please check, in your Plugin.php the elevated property is set to true. I updated it yesterday.
Then try to publish the api.php and jwt.php again.

**Comment by manojrammurthy** [comment]
Hi when i use middleware it throws error 
Class jwt.auth does not exist
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php line 752

**Comment by gpasztor87** [comment]
Hi @manojrammurthy.
I have fixed this problem, please try it again.

**Comment by manojrammurthy** [comment]
Thanks it works
