### ISSUE TITLE
trouble in the step jwt generate

### ISSUE THREAD

**Issue by mismaiti** [gpasztor87/oc-jwt-auth#7]
during this  ` php artisan jwt:generate`

i got this 

Method Tymon\JWTAuth\Commands\JWTGenerateCommand::handle() does not exist

did i missed something.. pls advise

**Comment by gpasztor87** [comment]
Maybe the tymon/jwt-auth dependency is not compatible with Laravel 5.5. 
They use the command classes in different ways. The fire() method has been renamed to handle(), which causes this error. I will update it soon.
